import { getLayout } from '../src/core/layout';
import { encodeFrameRGB, rasterize } from '../src/core/frameEncoder';
import { FrameDecoder } from '../src/core/frameDecoder';
import { Binarizer, findFinders, toGray } from '../src/core/detector';
import { capture, randomCamera } from '../src/sim/channel';
import { packTile, PACKET_SIZE } from '../src/core/tile';
const [W, H, bpc] = [Number(process.argv[2] ?? 256), Number(process.argv[3] ?? 144), Number(process.argv[4] ?? 3)];
const layout = getLayout({ width: W, height: H, bpc: bpc as 1 | 2 | 3, ecc: 1 });
const tiles = layout.tiles.map((_, i) => packTile({ session: 1, transferLength: 1000, packet: new Uint8Array(PACKET_SIZE).fill(i) }));
const screen = rasterize(layout, encodeFrameRGB(layout, tiles), 8);
const img = capture(screen, randomCamera(3, screen.width, screen.height, { width: 1920, height: 1080, fill: 0.85, severity: 'mild' }));
const dec = new FrameDecoder();
for (let i = 0; i < 3; i++) dec.decode(img);
const N = 10;
let t = performance.now();
for (let i = 0; i < N; i++) dec.decode(img);
for (let k = 0; k < 3; k++) { const rr = dec.decode(img); console.log(Object.entries(rr.timings).map(([k, v]) => `${k}=${v.toFixed(1)}`).join(' ')); }
console.log('full decode', ((performance.now() - t) / N).toFixed(1), 'ms', dec.decode(img).tilesOk, '/', layout.tiles.length);
const g = toGray(img.data, img.width, img.height);
t = performance.now();
for (let i = 0; i < N; i++) toGray(img.data, img.width, img.height, g.data);
console.log('gray', ((performance.now() - t) / N).toFixed(1));
const bz = new Binarizer();
t = performance.now();
for (let i = 0; i < N; i++) bz.run(g);
console.log('binarize', ((performance.now() - t) / N).toFixed(1));
t = performance.now();
for (let i = 0; i < N; i++) findFinders(bz.bin, img.width, img.height);
console.log('finders', ((performance.now() - t) / N).toFixed(1));
